### ISSUE TITLE
Entering visual mode does not update statusline

### ISSUE THREAD

**Issue by pinaki2** [vimpostor/vim-tpipeline#11]
Thank you for coming up with this plugin. I just installed it and was trying to use it. There are a couple of issues I am seeing.

1. I have multiple panes open in a tmux window, and I am currently in pane 1 where I have a file open in vim. Now if I switch to pane 2, the vim part of the status line does not change, that is, it still shows the vim status (filename, etc.) from the previous pane. If pane 2 also has a vim session open, then the status does change when I move the cursor. However, if pane 2 does not have an open vim session, then the vim part of the status line remains. (If instead of pane 2, I switch to a different window, then the same behavior is observed.)

2. If I switch to (line) visual mode by pressing V, the mode part of the status still shows NORMAL. Only if I move the cursor (like press j to highlight the line below too), it will update to V-LINE.

Terminal used is gnome-terminal.

I am using vim version 8.1. I have added the following lines in my .vimrc.
```
set termguicolors
let g:tpipeline_cursormoved = 1
set updatetime=300

set stl=%!tpipeline#stl#line()
let g:tpipeline_split = 1
```

I have added the following lines in my .tmux.conf.
```
set -g default-terminal "xterm-256color"

set -g focus-events on
set -g status-style bg=default
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 120
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right-length 120
set -g status-interval 0
set -g status-justify centre
set -g window-status-current-format "#[fg=colour4]\uE0B6#[fg=colour7,bg=colour4]#{?window_zoomed_flag,#[fg=yellow]🔍,}#W#[fg=colour4,bg=default]\uE0B4"
set -g window-status-format "#[fg=colour244]\uE0B6#[fg=default,bg=colour244]#W#[fg=colour244,bg=default]\uE0B4"
```

**Comment by vimpostor** [comment]
As for your first issue:

> I am using vim version 8.1

Vim 8.1 does not support focus events, therefore switching tmux panes will not trigger the needed autocmd to update the statusline. You need to update to vim `8.2.2345` and it will work or use `neovim` (which supports focus events for a long time).


Regarding the second issue, unfortunately vim does not provide any `autocmd` on Visual mode enter so there is no clean way to fix this. There are a few hacky workarounds like this possible: https://github.com/vim/vim/issues/1146#issuecomment-252503573

The best solution would be to implement a general ModeChange autocmd in upstream vim, but maybe I will find a better way to fix this from the plugin side than just polling...

**Comment by pinaki2** [comment]
Thanks! The first issue is solved as I installed the latest version of vim. Let me know if you come up with any solution for the second one.

**Comment by vimpostor** [comment]
> Let me know if you come up with any solution for the second one.

I have now implemented the necessary functionality for this upstream in both [vim](https://github.com/vim/vim/pull/8856) and [neovim](https://github.com/neovim/neovim/pull/15840).

The statusline should now update immediately when entering visual mode, if you use vim **8.2.3430** or neovim **0.6** (the neovim patch is still pending though).
