### ISSUE TITLE
Tmux background color is overwritten, even if vim statusline does not include any color definitions

### ISSUE THREAD

**Issue by atidyshirt** [vimpostor/vim-tpipeline#12]
How should I go about implementing this into my current statusline, I seem to be running into issues with colors of the files from vim, currently background color is incorrect as seen below.

<img width="472" alt="Screen Shot 2021-06-19 at 7 01 14 PM" src="https://user-images.githubusercontent.com/20514752/122634156-baf22980-d130-11eb-9949-7058968e6c5f.png">

relevant tmux code is:

```
set-option -g status-right '#[bg=colour237,fg=colour239 nobold, nounderscore, noitalics]#[bg=colour239,fg=colour246] #(cat #{socket_path}-\#{session_id}-vimbridge)  Vim #[bg=colour239,fg=colour248,nobold,noitalics,nounderscore]#[bg=colour248,fg=colour237] #h '
```

and using the following in my neovim config:

```
let g:tpipeline_statusline = '%!tpipeline#stl#line()'
let g:tpipeline_statusline = '%f'
```

I suspect it is todo with `let g:tpipeline_statusline = '%!tpipeline#stl#line()'` however deleting this seems to have little help

**Comment by vimpostor** [comment]
> and using the following in my neovim config:
> 
> ```
> let g:tpipeline_statusline = '%!tpipeline#stl#line()'
> let g:tpipeline_statusline = '%f'
> ```

You should only set `g:tpipeline_statusline` once, there is no need to set it twice. In your case above, the statusline will have the value `'%f'` at the end, so you can just drop the line above. If you just want to have your current statusline in tmux without any change, you do not need to set `g:tpipeline_statusline` at all.


As for your actual issue, this plugin does use the default `StatusLine` vim highlight color both as foreground and background color in the tmux statusline. This is meant to be a "sane" default to prevent users from not seeing any statusline at all, if they just use a simple statusline like `'%f'`.
However I do see your usecase (and I actually quite like the way you want to configure your statusline) and will add an option to disable that default behaviour of overwriting the tmux background color.

**Comment by atidyshirt** [comment]
Right, that was the conclusion I had reached, so as of now, the default behaviour is to take colour properties from your current status line (within vim) and apply them. I might have a fiddle with the code base and see if I can come up with some options that might be useful in a PR (I am in exams so not sure how much time I will have)

On another note, really enjoy the project, this is an awesome idea!

**Comment by vimpostor** [comment]
You can now get your desired behaviour by setting ` let g:tpipeline_preservebg = 1` in your `.vimrc`.

![Screenshot_20210619_120426](https://user-images.githubusercontent.com/21310755/122638799-83ff2200-d0f6-11eb-95df-96d8c854899a.png)

Thanks very much for reporting the issue, I actually quite like the idea of your statusline, I am wondering why I didn't add this option earlier.

**Comment by vimpostor** [comment]
> I might have a fiddle with the code base and see if I can come up with some options that might be useful in a PR (I am in exams so not sure how much time I will have)

Oh sorry, I didn't see that. Looks like I was faster with implementing that option, sorry!

**Comment by atidyshirt** [comment]
> You can now get your desired behaviour by setting ` let g:tpipeline_preservebg = 1` in your `.vimrc`.
> 
> ![Screenshot_20210619_120426](https://user-images.githubusercontent.com/21310755/122638799-83ff2200-d0f6-11eb-95df-96d8c854899a.png)
> 
> Thanks very much for reporting the issue, I actually quite like the idea of your statusline, I am wondering why I didn't add this option earlier.

thanks for that! Another thought I had is if it is possible to handle this all within vim? Because if that is the case, then it could eliminate the issue of having an empty block as shown below

<img width="261" alt="Screen Shot 2021-06-19 at 10 09 32 PM" src="https://user-images.githubusercontent.com/20514752/122638903-07e2f980-d14b-11eb-92ae-ef0b287f8d55.png">

also cheers for the help :)

**Comment by atidyshirt** [comment]
Also I appear to be facing the same issue with that specific case

<img width="790" alt="Screen Shot 2021-06-19 at 10 12 26 PM" src="https://user-images.githubusercontent.com/20514752/122638971-70ca7180-d14b-11eb-91b8-f498c26d84fd.png">

**Comment by vimpostor** [comment]
> thanks for that! Another thought I had is if it is possible to handle this all within vim?

Yes, you can achieve this behaviour by defining your own highlight groups in vim and using them. For example:
```vim
" vimrc
hi MyGrey guifg=#ffffff guibg=#9e9e9e
hi MyGreyInv guifg=#9e9e9e guibg=bg
let g:tpipeline_statusline = '%#MyGreyInv#%#MyGrey#%f  Vim %#MyGreyInv#'
```

```tmux
# tmux
set-option -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge)#[bg=#9e9e9e,fg=#5e5e5e,nobold,noitalics,nounderscore]#[bg=#5e5e5e,fg=#ffffff] #h '
```

Vim open:
![Screenshot_20210619_124100](https://user-images.githubusercontent.com/21310755/122639712-a2b3e780-d0fb-11eb-9628-94b4f7e2d1fb.png)

Vim not open:
![Screenshot_20210619_124725](https://user-images.githubusercontent.com/21310755/122639849-86fd1100-d0fc-11eb-8849-eff97db5a0fc.png)

The empty block is gone now, unfortunately the little triangle has the wrong background color now. To get rid of that is a little more complicated, I would have to experiment some more. Maybe one could use tmux conditionals in the statusline to render different triangles.
