### ISSUE TITLE
Respect color, intensity of status line

### ISSUE THREAD

**Issue by meijieru** [vimpostor/vim-tpipeline#16]
Currently the intensity of left/right section is ignored.
Also the middle doesn't respect the colors of the original statusline.

With tmux
![image](https://user-images.githubusercontent.com/9511136/142360347-d97f93df-d0b1-4a95-9d67-1a6cab58b364.png)

Without tmux
![image](https://user-images.githubusercontent.com/9511136/142360395-445e2098-8a21-4256-b129-bea0484b69b4.png)

**Comment by vimpostor** [comment]
Sorry, what do you mean with "intensity of left/right section"?

**Comment by meijieru** [comment]
If the original text is bold, it should be bold while it is normal in tmux statusline now.

**Comment by vimpostor** [comment]
Text intensity is now working out of the box:
<img width="953" alt="Screenshot_20211211_011510" src="https://user-images.githubusercontent.com/21310755/145656220-1cc1159b-de46-4f06-869f-3c2bd2d4d74d.png">

```bash
vim --clean -Nu <(cat<<EOF
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
hi Bold guifg=#ffffff guibg=#000000 gui=bold term=bold cterm=bold
hi Italic guifg=#ffffff guibg=#000000 gui=italic term=italic cterm=italic
hi Both guifg=#ffffff guibg=#000000 gui=italic,bold term=italic,bold cterm=italic,bold
hi Test guifg=#ffffff guibg=#000000
set stl=%#Test#Hello%#Bold#Bold%#Italic#Italic%#Test#Normal%=%#Italic#Italic%#Bold#Bold%#Test#Normal%#Both#Both%#Test#Normal
set runtimepath^=~/path/to/vim-tpipeline
au VimEnter * set laststatus=2
EOF
)
```

**Comment by vimpostor** [comment]
I will implement the part about respecting the color in the middle some time later, but it will probably become an option that is off by default. I think it is a more sane default to keep the tmux default statusline background color in the middle, as we would otherwise mess up the middle segment for some configurations (for example I believe my screenshot above would be messed up by such a change).

**Comment by vimpostor** [comment]
This plugin can now respect the color of the middle of the vim statusline and fill the middle of the tmux statusline with it. Activate the feature by using `let g:tpipeline_fillcentre = 1`.

<img width="836" alt="Screenshot_20211211_143929" src="https://user-images.githubusercontent.com/21310755/145678717-b72657e0-b222-43d0-80bb-10d00070d2c3.png">

**Comment by meijieru** [comment]
Works like a charm! Thx!
