### ISSUE TITLE
Statusbar duplicated for horizontal splits

### ISSUE THREAD

**Issue by TudorAndrei** [vimpostor/vim-tpipeline#19]
In the case of horizontal splits, the upper window has it's own statusline.

![image](https://i.imgur.com/axsyaEb.png)

**Comment by vimpostor** [comment]
Yeah, that one also annoys me.
Unfortunately it is impossible in vim to remove that line between horizontal splits completely. We can only change the text and color of that split line, but what color should the splitline be? I guess using a blank line that is colored with `hl-StatusLine` would be the best option, so basically the equivalent of `set stl=%#StatusLine#` after the plugin is loaded.
Another problem is that the default `fcs` option is kinda weird and shows `^` characters in the active split statusline unless `hl-StatusLine` is different from `hl-StatusLineNC`.

I can add an option that does this, but I am not sure if it should be on by default. As you can see in the screenshot below, the split line without anything in it looks a little weird. Perhaps something like the example on the right side would be a better default, although I kinda dislike plugins changing basic options like `fcs`.
![Screenshot_20211223_221704](https://user-images.githubusercontent.com/21310755/147292135-1786530d-58f5-494b-b757-7c2bd9a4e060.png)

If you have a better idea how to design the splitline, let me know!

**Comment by TudorAndrei** [comment]
Yeah, it's tricky and depends on what people like, so setting it by default wouldn't be an option. For me having the empty row between the "~" column feels cleaner.

**Comment by vimpostor** [comment]
Yes I agree, I have now added this feature but it's disabled by default. You can enable it with `let g:tpipeline_clearstl = 1`.
This plugin will not touch the `fillchars` setting, but if people dislike the empty split statusline, they can just set it themself e.g.:
```vim
set fcs+=stlnc:-
set fcs+=stl:-
```

**Comment by WilliamHsieh** [comment]
It works, mostly. However, the embedded part is no longer responsive. For example, `set stl=something` will change the split statusline to `something` but not the embedded part, whereas previously without the option both status line will change.
Not sure if this is the expected behaviour though. 😅
