### ISSUE TITLE
support global statusline

### ISSUE THREAD

**Issue by yamatsum** [vimpostor/vim-tpipeline#24]
https://github.com/neovim/neovim/issues/9342

**Comment by yamatsum** [comment]
in plugin.lua
```
vim.g.tpipeline_autoembed = 0
```

tmux.conf
```
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 90
set -g status-right "#(cat #{socket_path}-\#{session_id}-vimbridge-R) #[fg=#6a737d]#{?client_prefix,#[fg=#316DCA],}□"
set -g status-right-length 90
```
In the case of the above settings, it will be as follows.
<img width="1590" alt="CleanShot 2022-04-22 at 18 22 54@2x" src="https://user-images.githubusercontent.com/42740055/164677413-fdd48511-2ca5-484f-8f65-e2e10374824f.png">


But to the right of the real vim statuline is showing git branch information
<img width="1588" alt="CleanShot 2022-04-22 at 18 21 19@2x" src="https://user-images.githubusercontent.com/42740055/164677259-9447cda6-27ca-48a5-9ade-adc53c94af6f.png">

Maybe the global status line doesn't matter

**Comment by vimpostor** [comment]
I tried your config, but I cannot reproduce unfortunately, it works for me:

![Screenshot_20220422_133528](https://user-images.githubusercontent.com/21310755/164707093-8b04697c-ac06-4149-90e7-dcee9a57ac6e.png)

What version of neovim are you using?
Can you perhaps provide more detailed steps on how to reproduce this? Maybe I need your entire vim config to reproduce this.

**Comment by vimpostor** [comment]
Oh I forgot to use your manual embed step, I can reproduce now. In your `set -g status-right` command you are using double quotes `"`, but you need to use single quotes `'` like the documentation says, or alternatively escape problematic characters.

```diff
-set -g status-right "#(cat #{socket_path}-\#{session_id}-vimbridge-R) #[fg=#6a737d]#{?client_prefix,#[fg=#316DCA],}□"
+set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R) #[fg=#6a737d]#{?client_prefix,#[fg=#316DCA],}□'
```

**Comment by yamatsum** [comment]
It was my mistake!
Thank you!

**Comment by vimpostor** [comment]
On a related note, I don't understand why all these statuslines like lualine add their own `globalstatus` option, when they can just use the official `laststatus = 3` option. When you go look at the PR that supposedly implements "global statusline" support for lualine and take a look at the code, then you will see that all it does is set `laststatus` to `3` if `globalstatus` is true, which is ridiculous, since the user could just directly set `laststatus`.
