### ISSUE TITLE
can not show :'<,'> after select multiple line

### ISSUE THREAD

**Issue by ShiChenCong** [vimpostor/vim-tpipeline#28]
### Describe the bug

![Untitled](https://user-images.githubusercontent.com/22486446/174931073-39d65c4d-0a2f-4576-9f08-b00e2b88a3b2.gif)

### Expected behavior

show info

### Vim version

NVIM v0.8.0-dev+1918-g34ae896b8

### Tmux version

tmux 3.3a

### Terminal emulator

kitty

### Debug output

```JSON
{'right': ['#[fg=#CAD3F5,bg=#1E2030]#[fg=#cbcb41,bg=#1e2030] #[f
g=#cad3f5,bg=#1e2030] javascript #[fg=#494d64,bg=#1e2030]#[fg=#f
5a97f,bg=#494d64] 100% #[fg=#f5a97f,bg=#494d64]#[fg=#24273a,bg=#
f5a97f,bold]   6:1  '], 'native_str': ' NORMAL                  
           javascript  100%    6:1  ', 'left': ['#[fg=#CAD3F5,
bg=#1E2030]#[fg=#24273a,bg=#f5a97f,bold] COMMAND #[fg=#f5a97f,bg=
#1e2030,nobold]#[fg=#cad3f5,bg=#1e2030]'], 'native_highlights': 
[{'group': 'lualine_a_normal', 'start': 0}, {'group': 'lualine_tr
ansitional_lualine_a_normal_to_lualine_c_normal', 'start': 8}, {'
group': 'lualine_c_normal', 'start': 11}, {'group': 'lualine_x_fi
letype_DevIconJs_normal', 'start': 37}, {'group': 'lualine_c_norm
al', 'start': 41}, {'group': 'lualine_transitional_lualine_b_norm
al_to_lualine_c_normal', 'start': 53}, {'group': 'lualine_b_norma
l', 'start': 56}, {'group': 'lualine_transitional_lualine_a_norma
l_to_lualine_b_normal', 'start': 62}, {'group': 'lualine_a_normal
', 'start': 65}]}
```

**Comment by vimpostor** [comment]
Sry, I don't understand the bug. What exactly are you expecting to see? Isn't the problem with the cmdline? The statusline looks perfectly normal to me.

**Comment by vimpostor** [comment]
Is this with `cmdheight=0`? You could test if you still have this problem when using https://github.com/neovim/neovim/pull/18961

**Comment by ShiChenCong** [comment]
Sorry for my poor english，yes，looks like cmdline problem
![image](https://user-images.githubusercontent.com/22486446/175000244-d777e45a-e20a-4ae8-b0e7-2f90c9f5fad2.png)
should show  `:'<,'>`

**Comment by vimpostor** [comment]
> yes, looks like cmdline problem

Then the problem should be reported at neovim. I can't reproduce it, so maybe it's already fixed in neovim master.
