### ISSUE TITLE
Cannot disable this plugin when running nvim on gui

### ISSUE THREAD

**Issue by lourenci** [vimpostor/vim-tpipeline#29]
### Describe the bug

First of all, thank you for this plugin.

Sometimes, I want to run `nvim` in a GUI environment, thus wanting to restore my default status line. I've tried to use both calls when there is `gui_running`, but both seem not to be working:

```
let g:tpipeline_autoembed = 0
tpipeline#state#freeze()
```

Is there any way to disable this plugin in that use case?

**Comment by vimpostor** [comment]
It will work by default now.
