### ISSUE TITLE
use pipe line to show tabline

### ISSUE THREAD

**Issue by windwp** [vimpostor/vim-tpipeline#3]
let g:tpipeline_statusline = &tabline
i want to combine tabline with tmux line on top then display status line on bottom.

i try to use that method 
let g:tpipeline_statusline = &tabline
but it still have  issue

- [ ]  i need to run that script in command . it doesn't have any effect when put it on vimrc
- [ ]  tabline is not hide and it hide status line

**Comment by vimpostor** [comment]
You can now instead put `let g:tpipeline_tabline = 1` in your `.vimrc` to make this plugin copy your tabline instead of the statusline. Let me know if you still have any problems. :)
