### ISSUE TITLE
Not working with lualine

### ISSUE THREAD

**Issue by AdamBremholm** [vimpostor/vim-tpipeline#32]
### Describe the bug

Lualine becomes hidden when installing this plugin and I can only see tmux windows information in the statusline.
When uninstalling the plugin lualine shows up again and tmux windows are shown under the statusline as expected. 
I am using the default config for lualine.
The plugin works fine when used with the built in statusline. 

### Expected behavior

Be able to see both lualine and tmux info in the same statusline

### Vim version

NVIM v0.8.0-dev

### Tmux version

tmux 3.0a

### Terminal emulator

Windows Terminal

### Debug output

```JSON
{'right': [''], 'native_str': '', 'left': ['#[fg=#a9b1d6,bg=#16161e]#[fg=,bg=terminal]'], 'native_highlights': [{'group': 'Normal', 'start': 0}]}
```

**Comment by vimpostor** [comment]
This usually worked with lualine, I have bisected the first bad lualine commit to [53aa3d82d9d9329880b4197f278fcb74051a6af5](https://github.com/nvim-lualine/lualine.nvim/commit/53aa3d82d9d9329880b4197f278fcb74051a6af5) introduced with https://github.com/nvim-lualine/lualine.nvim/pull/736.

I still think its the fault of my plugin though, I need to see how to fix it in the best way without breaking previous configurations.
