### ISSUE TITLE
On i3 - Alacritty, statusline disappear after switching workspace

### ISSUE THREAD

**Issue by krehwell** [vimpostor/vim-tpipeline#34]
### Describe the bug

On i3, Using Alacritty, when I switch between workspace the statusline disappear. In order to make it appear again, on vim I have to enter the command mode (`:`) or switch to another buffer

### To reproduce

On i3:

1. open terminal
2. start tmux session
3. open vim, notice that vim-tpipeline working normally
4. switch to another workspace (example: mod + 3)
5. switch back to workspace where vim is currently opened, notice that now the vim-tpipeline disappear

### Expected behavior

The statusline remain there and should not disappear

### Vim version

NVIM v0.7.2

### Tmux version

tmux 3.3a

### Terminal emulator

Alacritty

### Debug output

```JSON
{'right': ['#[fg=,bg=#303030]'], 'native_str': '', 'left': ['#[fg=,bg=#303030]#[fg=#3b4252,bg=#88c0d0] COMMAND #[fg=#88c0d0,bg=#3b4252]#[fg=#e5e9f0,bg=#3b4252] i3 | /in
it.vim #[fg=#3b4252,bg=#444444]#[fg=#444444,bg=#444444]'], 'native_highlights': [{'group': 'StatusLine', 'start': 0}]}
```

**Comment by vimpostor** [comment]
That's weird, looks like vim-tpipeline is not getting the Focus Event.

Can you try the following both outside and inside tmux:

- Start vim
- `:autocmd FocusLost * echom 'Focus lost'`
- `:autocmd FocusGained * echom 'Focus gained'`
- Switch to another workspace
- Switch back to previous workspace
- Observe if the message 'Focus gained' was printed

**Comment by krehwell** [comment]
I can get the `Focus gained`

**Comment by krehwell** [comment]
btw, here is the screen record of the issue
![issue](https://user-images.githubusercontent.com/54220436/186615607-9ae3fc52-51fb-4f24-a0c4-28d643f41851.gif)

**Comment by vimpostor** [comment]
Would you mind giving me your i3 config? I want to try reproduce this myself.

**Comment by krehwell** [comment]
here you go: https://github.com/krehwell/dotfiles/blob/i3/.config/i3/config

**Comment by krehwell** [comment]
Hey, I think I have found the issue:

on my init.vim I have this config for some reason
``` vimscript
autocmd VimLeavePre * :call coc#rpc#kill()
autocmd VimLeave * if get(g:, 'coc_process_pid', 0) | call system('kill -9 -'.g:coc_process_pid) | endif
```

I just removed that and everything works normally now. my bad I thought something is wrong with the plugin.

thanks you very much for your awesomeness!

**Comment by vimpostor** [comment]
Thanks it was very easy to reproduce the problem with your config.

It looks like there is a bug in i3 that pushes nonsense focus events on workspace switching.
If you open vim and setup the following autocmds:

```vim
autocmd FocusGained * echom "gained focus at " . reltimestr(reltime())
autocmd FocusLost * echom "lost focus at " . reltimestr(reltime())
```

And then switch to another workspace, wait there for 5 seconds and then switch back to vim, you will get the following output:

```
lost focus at 1661509490.388957
gained focus at 1661509495.143829
lost focus at 1661509495.246055
gained focus at 1661509495.246184
```

The first two events are correct, there is a 5 second difference inbetween. The last two focus events are absolute nonsense and redundant, it seems that i3 posts two additional focus events in rapid succession, which happen to very likely trigger a race condition in this plugin.

I will fix the race condition, but it is important to know that i3 is also not quite behaving correctly here.

**Comment by krehwell** [comment]
you are aweesomee!!!
