### ISSUE TITLE
Extending functionality to use with Kitty Tab-Bar

### ISSUE THREAD

**Issue by primeapple** [vimpostor/vim-tpipeline#35]
I really like this plugin, I think it's an awesome idea!

Did you think about extending this to work with other Statuslines, like the tab-bar of the Kitty Terminal? I'ts quite customizable: see https://sw.kovidgoyal.net/kitty/conf/#tab-bar , especially the `custom` option of `tab_bar_style`.

What are your opinions on this?

**Comment by vimpostor** [comment]
I have thought about this already as well, some mechanism would be good where the user could define a custom external statusline sink.
Then it could be possible to also embed the statusline in the i3 statusline for example.

**Comment by vimpostor** [comment]
OK I have implemented a prototype of this, but it might be a bit janky. The statusline you see at the bottom of the screenshot is neither the tmux statusline nor the vim statusline, it is the kitty tab-bar!

![Screenshot_20220828_224821](https://user-images.githubusercontent.com/21310755/187093919-068e96a2-da14-4de0-b4af-efca4c730a3e.png)


Do you perhaps know how to trigger a refresh of the kitty tab-bar from the outside with a shell command? `kitty @ set-tab-title Master ""` does not seem to work for me, so right now I am using a hacky timer to update it.

Here is how to accomplish this:

### vimrc
```vim
let g:tpipeline_refreshcmd = "kitty @ set-tab-title Master test"
```

### kitty.conf

```conf
tab_bar_style custom
tab_bar_min_tabs 1
tab_separator ""
```

### ~/.config/kitty/tab_bar.py

<details>
  <summary>Show code</summary>

```python
import os
from kitty.boss import get_boss
from kitty.fast_data_types import Screen, add_timer
from kitty.tab_bar import DrawData, ExtraData, TabBarData, draw_title, as_rgb
from kitty.utils import color_as_int

timer_id = None

def parse_stl(screen: Screen, draw_data: DrawData, stl: str, draw: bool):
	pos = 0
	length = 0
	while pos < len(stl):
		next = stl.find("#[", pos)
		if next == -1:
			length += len(stl[pos:])
			if draw:
				screen.draw(stl[pos:])
			return length

		length += len(stl[pos:next])
		if draw:
			screen.draw(stl[pos:next])
		pos = next + 1
		next = stl.find("]", pos)
		if next == -1:
			length += len(stl[pos:])
			if draw:
				screen.draw(stl[pos:])
			return length

		fmt = stl[pos+1:next].split(",")
		for f in fmt:
			if f.startswith("fg="):
				if f == "fg=default":
					screen.cursor.fg = as_rgb(int(draw_data.default_fg))
				else:
					screen.cursor.fg = as_rgb(int(f[4:10], 16))
			elif f.startswith("bg="):
				if f == "bg=default":
					screen.cursor.bg = as_rgb(int(draw_data.default_bg))
				else:
					screen.cursor.bg = as_rgb(int(f[4:10], 16))

		pos = next + 1

	return length

def draw_tpipeline(screen: Screen, draw_data: DrawData):
	stl = open('/tmp/tmux-' + str(os.getuid()) + '/default-$0-vimbridge').readline()
	parse_stl(screen, draw_data, stl, True)
	stl = open('/tmp/tmux-' + str(os.getuid()) + '/default-$0-vimbridge-R').readline()
	length = parse_stl(screen, draw_data, stl, False)
	screen.draw(" " * (screen.columns - screen.cursor.x - length))
	length = parse_stl(screen, draw_data, stl, True)

def redraw_tab_bar(timer_id):
	tm = get_boss().active_tab_manager
	if tm is not None:
		tm.mark_tab_bar_dirty()

def draw_tab(
		draw_data: DrawData, screen: Screen, tab: TabBarData,
		before: int, max_title_length: int, index: int, is_last: bool,
		extra_data: ExtraData
		) -> int:

	global timer_id
	if timer_id is None:
		timer_id = add_timer(redraw_tab_bar, 0.3, True)

	if index == 1:
		draw_tpipeline(screen, draw_data)

	return screen.cursor.x
```

</details>

**Comment by primeapple** [comment]
Thanks, I'll have a look into this :)

**Comment by vimpostor** [comment]
The only problem right now is that I update the kitty statusline with the timer, which is not a pleasant user experience due to the delay. If you find a way how to make `kitty @ set-tab-title Master test` work (i.e. update the statusline on demand), let me know.

**Comment by primeapple** [comment]
I looked into this issue today.
Sorry for taking overly long.

There is good news:

It is actually possible to update the kitty tab bar on command. `kitty @ set-tab-title Master test` actually works perfectly and calls the `draw_tab` function when using `let g:tpipeline_refreshcmd = "kitty @ set-tab-title Master test"`.

You can check this out with the following `tab_bar.py` file:

```python
from kitty.fast_data_types import Screen
from kitty.tab_bar import (DrawData, ExtraData, TabBarData)
import datetime

def draw_tab(
		draw_data: DrawData, screen: Screen, tab: TabBarData,
		before: int, max_title_length: int, index: int, is_last: bool,
		extra_data: ExtraData
		) -> int:
    print("redrawing tab")
    print(datetime.datetime.now())

    return index
```

Now run `kitty` from another terminal. In this one, you'll see the print outputs.
In the opened kitty terminal, open (Neo)vim, and do things. You'll see, that kitty redraws the tab bar :)


The one thing I'm missing now is an actual nice tabbar in Kitty. I'll try to work on this. If you can help further with this, let me know :)

**Comment by vimpostor** [comment]
> kitty @ set-tab-title Master test` actually works perfectly and calls the `draw_tab` function when using `let g:tpipeline_refreshcmd = "kitty @ set-tab-title Master test"`.

Weird, it doesn't actually work for me. I tried your above `tab_bar.py` file and I only see the `"redrawing tab"` irregularly, definitely not on every neovim statusline update, I don't know why it works for you.

I can't get it to update automatically without [the timer](https://github.com/vimpostor/vim-tpipeline/issues/35#issuecomment-1229551519)...

**Comment by primeapple** [comment]
Ahh, can you try adding the following to your kitty.conf:

```
allow_remote_control yes
listen_on unix:@mykitty
```
Assuming you are on linux, on other unixes it should be
```
allow_remote_control yes
listen_on unix:/tmp/mykitty
```
```

**Comment by vimpostor** [comment]
> Ahh, can you try adding the following to your kitty.conf:
> 
> ```
> allow_remote_control yes
> listen_on unix:@mykitty
> ```

Ah thanks, now it does indeed work without the timer. Seems to be working quite well now too.

**Comment by primeapple** [comment]
I'm fine if there is the same functionality as with TMUX. So it should be able to show the Kitty Tabs, probably centered.

Couple things to worry about:

By default kitty does not show the tabbar when there is only one tab, see [tab_bar_min_tabs](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.tab_bar_min_tabs). We will either have to disable this or think of some advanced logic, to show the normal statusline in VIM, when there is only 1 tab.

We also have to show the normal Statusline (in vim) when not running inside Kitty

**Comment by vimpostor** [comment]
> By default kitty does not show the tabbar when there is only one tab, see [tab_bar_min_tabs](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.tab_bar_min_tabs).

Yeah, that's why I said [here](https://github.com/vimpostor/vim-tpipeline/issues/35#issuecomment-1229551519), that `tab_bar_min_tabs 1` is needed in `kitty.conf` ;)

I think you can then mostly put the default kitty tabbar in the middle of the tabbar, and the result should be pretty reasonable.
