### ISSUE TITLE
Restore original tmux status after switching to a non-vim window

### ISSUE THREAD

**Issue by WilliamHsieh** [vimpostor/vim-tpipeline#37]
### Describe the bug

Is there a way to restore the original tmux status line (both status-left and status-right) after switching to a non-vim tmux window?

### To reproduce

1. enter tmux
2. start vim / nvim in a window
3. switch to another tmux window
4. both status-left and status-right are gone

### Expected behavior

There should be a way to restore the user-defined status-left and status-right after switching out of vim.

### Terminal emulator

alacritty

**Comment by vimpostor** [comment]
Yes, does `let g:tpipeline_restore = 1` not work for you?

**Comment by WilliamHsieh** [comment]
It works! Thank's for your fast response!

**Comment by sm00k3y** [comment]
Is it possible to put this in the readme? I was looking for that option for way too long 🙏 

Anyways, amazing plugin, thank you so much for it!
