### ISSUE TITLE
Bufferline hover feature isn't working

### ISSUE THREAD

**Issue by WilliamHsieh** [vimpostor/vim-tpipeline#39]
### Describe the bug

[This](https://github.com/akinsho/bufferline.nvim#hover-events) is a feature implemented by bufferline. If I remove `tpipeline` from the plugin list I used, everything works fine. Not sure what happened.

### To reproduce

1. nvim -nu min.lua <file1> <file2>
2. point the cursor toward a buffer tab (like the demo in bufferline link)
3. If you comment out `tpipeline` in the following `min.lua`, everything works fine.

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      {
        'akinsho/bufferline.nvim',
        tag = "v3.*",
        requires = 'kyazdani42/nvim-web-devicons',
        config = function()
          require("bufferline").setup {
            options = {
              hover = {
                enabled = true,
                delay = 100,
                reveal = { 'close' },
              }
            }
          }
        end,
      },
      {
        "vimpostor/vim-tpipeline",
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end

vim.opt.mousemoveevent = true
load_plugins()
require("packer").sync()
```

### Expected behavior

Works as bufferline intended.

### Terminal emulator

Alacritty

**Comment by vimpostor** [comment]
From a quick look at the source code, it looks like this is actually a bug in `bufferline.nvim`: https://github.com/akinsho/bufferline.nvim/blob/a703bb919aeb436eaa83bcbefdac51fbb92b4c74/lua/bufferline/hover.lua#L13

They are actively disabling the hover feature, if `laststatus=0`.

**Comment by vimpostor** [comment]
I have fixed this now upstream: https://github.com/akinsho/bufferline.nvim/pull/616
