### ISSUE TITLE
not working properly with xterm and themed zsh

### ISSUE THREAD

**Issue by gshpychka** [vimpostor/vim-tpipeline#4]
I'm on arch. Using xterm, zsh with oh-my-zsh, and the agnoster theme.

When I launch tmux with the config lines from the readme, the status line becomes almost invisible:

https://i.imgur.com/emSkqOj.png

I'm not doing to describe here what happens when I launch vim, because the issue is more fundamental than that. It's not even the plugin, this seems to be my tmux/terminal/shell setup.

**Comment by vimpostor** [comment]
Can you please paste your entire tmux config?
Then I could try it out on my own system.

Does it get any better if you also add the following to your config?
```bash
set -g window-status-current-format "#[fg=colour4]\uE0B6#[fg=colour7,bg=colour4]#{?window_zoomed_flag,#[fg=yellow]🔍,}#W#[fg=colour4,bg=default]\uE0B4"
set -g window-status-format "#[fg=colour244]\uE0B6#[fg=default,bg=colour244]#W#[fg=colour244,bg=default]\uE0B4"
```

**Comment by gshpychka** [comment]
Hm, I updated to tmux 3.2rc and that issue is no longer present. My entire config was just the lines in the readme, plus setting the default terminal to screen-256color.

I'm having a different issue with tmux 3.2rc, this time inside vim, I'll create a separate issue for that.
