### ISSUE TITLE
Only statusline text is preserved, colors/theming are not (neovim/airline)

### ISSUE THREAD

**Issue by gshpychka** [vimpostor/vim-tpipeline#5]
.tmux.conf

```
set-option -g default-terminal "screen-256color"

set -g focus-events on
set -g status-bg default
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-right-length 120
set -g status-interval 0
```

tmux version, as reported by pacman: `9173_3.2.rc.r118.g742e6708-1`.

Statusline: `vim-airline`, `vim-airline-themes`

airline config:

```
let g:airline_theme='gruvbox'
let g:airline_powerline_fonts=1

let g:airline_extensions = ['branch', 'hunks', 'vista', 'tabline']
let g:airline#extensions#tabline#enabled = 1
```

Terminal: `xterm 366-1`

Here's what my airline looks like normally:
https://i.imgur.com/OhrfoL4.png
Here's what it looks like with the plugin:
https://i.imgur.com/Hk8Qyau.png

**Comment by vimpostor** [comment]
I cannot reproduce this with the same tmux config in Konsole. Can you share your xterm config? Then I can test this inside xterm.

**Comment by gshpychka** [comment]
Here's my Xresources file for xterm:

```
xterm*faceName: JetBrainsMono Nerd Font Mono:style=Regular
xterm*faceSize: 12
xterm*VT100*renderFont: true

! gruvbox theme
! hard contrast: *background: #1d2021
*background: #1d2021
! default: *background: #282828
! soft contrast: *background: #32302f
*foreground: #ebdbb2
! Black + DarkGrey
*color0:  #282828
*color8:  #928374
! DarkRed + Red
*color1:  #cc241d
*color9:  #fb4934
! DarkGreen + Green
*color2:  #98971a
*color10: #b8bb26
! DarkYellow + Yellow
*color3:  #d79921
*color11: #fabd2f
! DarkBlue + Blue
*color4:  #458588
*color12: #83a598
! DarkMagenta + Magenta
*color5:  #b16286
*color13: #d3869b
! DarkCyan + Cyan
*color6:  #689d6a
*color14: #8ec07c
! LightGrey + White
*color7:  #a89984
*color15: #ebdbb2
```

**Comment by vimpostor** [comment]
Even in xterm and with your config I can't reproduce this. So it must be the vim config.

Can you try adding the following to your vimrc:
```vim
if has('termguicolors') "true colors
	let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
	let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
	set termguicolors
endif
```

**Comment by gshpychka** [comment]
That works! Although I had to use the alternative config with "split" from the readme, otherwise the statusline would be squeezed into the right half of the screen.

**Comment by vimpostor** [comment]
Maybe I should change the default from not-split to split, most people will probably want their statusline still having a left and right part separately.
