### ISSUE TITLE
The whole bar collapses to the left

### ISSUE THREAD

**Issue by willbou1** [vimpostor/vim-tpipeline#52]
Neovim version: v0.9.0-dev-1193+ga7cd79349
Tmux version: 3.3_a-3

Tmux configuration
```
set -g focus-events on
set -g status-style bg=default
set -g status-left-length 90
set -g status-right-length 90
set -g status-justify absolute-centre
```
TPipeline configuration
`g.tpipeline_restore = 1`

Nvim status line plugin: lualine

Here is a picture of my problem:
![image](https://user-images.githubusercontent.com/6372967/229315405-3e28a918-ea58-463c-9ec6-7c7365424b9c.png)
As you can see, both the left and right part of the nvim status line collapse to the left.

**Comment by vimpostor** [comment]
Please post the output of
- `:echo tpipeline#debug#info()`
- `:echo g:tpipeline_size`
- `:echo(str2nr(system("tmux display-message -p '#{window_width}'")))`

**Comment by willbou1** [comment]
![image](https://user-images.githubusercontent.com/6372967/229323201-7ca7b511-9401-4de1-b71c-5da014720f83.png)
![image](https://user-images.githubusercontent.com/6372967/229323208-85bf7549-3f6c-4792-954b-93366296aabe.png)
![image](https://user-images.githubusercontent.com/6372967/229323214-07a318ea-f2b9-467c-ac81-edf25b1f3fad.png)

**Comment by vimpostor** [comment]
Can you post the entire output of `:echo system("tmux display-message -p '#{window_width}'")`?
If there is no output, what happens when you run `tmux display-message -p '#{window_width}'` in your shell outside of vim?

**Comment by willbou1** [comment]
![image](https://user-images.githubusercontent.com/6372967/229323446-1cf2d6d5-d6f7-4ac8-b2a9-238a935a0f74.png)
![image](https://user-images.githubusercontent.com/6372967/229323467-6efdc32f-4aa9-4738-ad48-1cb99ac4f247.png)

**Comment by vimpostor** [comment]
> ^[[H^[[J^[[3J97

Looks like your shell is inserting some escape codes, could you post your shell configuration here?

**Comment by willbou1** [comment]
What do you need exactly? My shell config is kinda long. I use fish in a kitty terminal.

**Comment by vimpostor** [comment]
Can you please confirm that it works now as of the last commit?

**Comment by willbou1** [comment]
I'm still having the same problem unfortunately.

**Comment by vimpostor** [comment]
Sorry I forgot something, could you test again?

**Comment by willbou1** [comment]
OMG it works. You fixed it real fast haha Thank you! Now, I'm curious to know what the problem was. I'll take a look at your commit.

**Comment by willbou1** [comment]
The restore functionality seems to garble the left and right statuses too btw, but that's another problem.

**Comment by vimpostor** [comment]
> The restore functionality seems to garble the left and right statuses too btw, but that's another problem. Something in my setup must be really weird idk.

Could you post a screenshot of what is garbled after restore?

**Comment by willbou1** [comment]
Just after quitting NVIM
![image](https://user-images.githubusercontent.com/6372967/229362535-743262ee-8d5f-4e76-804b-52e340e27620.png)

**Comment by willbou1** [comment]
Works exactly as intended. Thank you and have a nice day!
