### ISSUE TITLE
NvChad: Statusbar duplicated in horizontal split

### ISSUE THREAD

**Issue by rhenzel** [vimpostor/vim-tpipeline#59]
### Describe the bug

Using neovim 0.10 & latest NvChad distro, I am unable to get rid of the horizontal doubled statusbar using `let g:tpipeline_clearstl = 1`, still looks as full

<img width="923" alt="example" src="https://github.com/vimpostor/vim-tpipeline/assets/39679591/3e36466c-034f-4765-9d1e-2e56b397239b">

### To reproduce

- Install NvChad 
- Install tpipeline via lazy.vim
- Run `let g:tpipeline_clearstl = 1`

### Expected behavior

Having only one global statusbar in the Tmux statusbar line.

### Terminal emulator

Alacritty

**Comment by vimpostor** [comment]
What is the output of `:verbose set stl`? I suspect that NvChad is interfering with the stl again after this plugin cleared it.

Does it work if you put the following autocmd in your vim config?
```vim
au OptionSet statusline call tpipeline#lualine#delay_eval()
```

Also NvChad is a giant distro, this is not really a nice minimal reproducible example.

**Comment by rhenzel** [comment]
Thanks for the help!

The output of `:verbose set stl` is
```
  statusline=%!v:lua.require('nvchad.statusline.minimal').run()
        Last set from Lua
```
[statusline source](https://github.com/NvChad/ui/blob/v2.0/lua/nvchad/statusline/minimal.lua)

Setting the autocmd did not help.
Naively and without success, I tried to change `tpipeline.vim` to
```
			if 1
				au OptionSet statusline call tpipeline#lualine#delay_eval()
				au ModeChanged * call tpipeline#lualine#fix_stl()
				set laststatus=0
```

> Also NvChad is a giant distro, this is not really a nice minimal reproducible example.  

Understood, felt it is worth raising since it is one of the most popular distros but understand if that won't be catered.

**Comment by rhenzel** [comment]
Figured it out probably was calling the code at the wrong time, adding the following lines to my `custom/init.lua` did the trick

```
vim.g.tpipeline_clearstl = 1
vim.o.fcs = "stlnc:─,stl:─,vert:│"
vim.opt.fillchars:append({ eob = " " })
```

**Comment by vimpostor** [comment]
Cool that you were able to fix the problem. I think this might be a common problem, when using lazy.nvim but I am not sure.
