### ISSUE TITLE
Kitty integration broke because of newline

### ISSUE THREAD

**Issue by primeapple** [vimpostor/vim-tpipeline#65]
### Describe the bug

As you may know I use the kitty tabbar and include the vim statusbar there with the help of your plugin.
Recently it somehow broke. I still don't know why it suddenly stopped working, but found the issue to be a newline at the end of each `readline()` call. I fixed the issue for my config in this commit https://github.com/primeapple/dotfiles/commit/a8394aa226a1b899566a288f9e65aa13cb61e94b .
I also tried your config but got the same problem.

I would appreciate if you could have a look into the config and test it out yourself to see if you face the same issue.

### To reproduce

Use the suggested kitty integration config. After opening (neo)vim, no statusbar is shown.

### Terminal emulator

kitty

**Comment by vimpostor** [comment]
Thanks for shaving that yak, you saved me quite some time debugging this change in kitty.
This should be fixed now.

BTW is there any advantage of your own tabbar script for kitty? Maybe we could merge back some changes, if you made some other improvements.

**Comment by primeapple** [comment]
I changed it so that the tabs are always in the middle of the tabbar. Also I cleaned up the code a bit and made it easier adding custom components.

Now it looks pretty similar to your TMUX config.

Have a look at it here: https://github.com/kovidgoyal/kitty/discussions/4447#discussioncomment-8575542 (sorry for the video, images didn't work :D)
