### ISSUE TITLE
Display Git Branch

### ISSUE THREAD

**Issue by felixkreuk** [vimpostor/vim-tpipeline#7]
Hi, thanks for the awesome plugin! Is it possible to display the git branch in the built-in status line?
Thanks

**Comment by vimpostor** [comment]
To be honest I want to keep the built-in status line as minimal as possible. I don't want to add too much statusline complexity as this plugin focuses on the tmux feature.
That being said I do acknowledge that this is probably something that many people want. I guess it won't hurt if I add another more reasonable statusline or at least make the statusline more easily configurable.
For a quick fix, it is already possible to kinda extend the statusline:

```vim
func mycustomwidget()
    return 'custom function'
endfunc

func myline()
	return tpipeline#stl#mode() . ' ' . tpipeline#stl#fn() . tpipeline#stl#attr() . '%=' . tpipeline#stl#ft() . ' ' . tpipeline#stl#progress() . mycustomwidget()
endfunc

set stl=!myline()
```

But I might add another default statusline which includes a git branch and maybe coc.nvim features.

**Comment by felixkreuk** [comment]
I totally get your point on keeping it minimal with the original goal.
On the other hand, it does seem like something that is quite basic (I would argue that on the same level as displaying the file name).
Thanks for the help, very cool plugin :)
