### ISSUE TITLE
Not working with Airline

### ISSUE THREAD

**Issue by sgalizia** [vimpostor/vim-tpipeline#8]
I tried getting this to work with `vim-airline` and it does not appear to work. I followed your recommended config in the README and all I see is the normal tmux statusline. The only difference being that my airline statusline is now gone.

With tpipeline installed:
![image](https://user-images.githubusercontent.com/1574010/109035396-758b8700-767d-11eb-8024-3ebf7fab7d34.png)

My normal statusline with tmux:
![image](https://user-images.githubusercontent.com/1574010/109035800-d87d1e00-767d-11eb-9f91-77b669eeedf5.png)

**Comment by vimpostor** [comment]
Hmm for me it's working, can you please share your vim and tmux config and tell me what terminal you are using?

**Comment by sgalizia** [comment]
I am using Windows Terminal with WSL 2 - Ubuntu 20.10 I have my config setup in a dotfiles repo here on GitHub. Would it be easiest to just link you to that for the config?

**Comment by vimpostor** [comment]
From a quick glance at your dotfiles it looks like `Plug 'edkolev/tmuxline.vim'` is the culprit. Of course this plugin won't work with another plugin together that already sets your tmux statusline to something else.

**Comment by sgalizia** [comment]
🤦🏻 you are so right. Sorry about the confusion! 😆 I feel a little dumb it was so obvious
