### ISSUE TITLE
pathogen support

### ISSUE THREAD

**Issue by willyspinner** [vimpostor/vim-tpipeline#9]
Hello,

First of all, this is a really neat plugin! 

Is it possible to install `vim-tpipeline` using pathogen? I'm using pathogen as the main method to install vim plugins.

Thanks!

**Comment by vimpostor** [comment]
Yes sure, you can install it with pathogen just like any other plugin using:

```bash
cd ~/.vim/bundle
git clone https://github.com/vimpostor/vim-tpipeline.git
```
